[package]
name = "camera-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
base64 = "0.22"
bytes = "1.10"
chrono = { version = "0.4", default-features = false, features = ["clock", "std"] }
libc = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha1 = "0.10"
tokio = { version = "1.45", features = ["rt", "sync", "time"] }
webrtc = { git = "https://github.com/gengwenguan/webrtc", rev = "a91689c3dd237ea48a0ce5a827a69d3807420a5c" }

[build-dependencies]
cc = "1.2"

[profile.release]
codegen-units = 1
lto = "thin"
opt-level = "s"
panic = "abort"
strip = "symbols"
